export interface ISideBarOptions {
  id: number;
  name: string;
  iconName: string;
  colorLight: string;
  colorActiveLight: string;
  colorDark: string;
  colorActiveDark: string;
}
export const SIDEBAR_CATEGORIES: ISideBarOptions[] = [
  {
    id: 1,
    name: 'Popular',
    iconName: 'gb-popular',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#007354',
    colorActiveDark: '#007354',
  },
  {
    id: 2,
    name: 'Favorites',
    iconName: 'gb-star',
    colorLight: '#FFBF2E',
    colorDark: '#FFBF2E',
    colorActiveLight: '#FFBF2E',
    colorActiveDark: '#FFBF2E',
  },
  {
    id: 3,
    name: 'Football',
    iconName: 'gb-football',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#007354',
    colorActiveDark: '#007354',
  },
  {
    id: 4,
    name: 'Tennis',
    iconName: 'gb-tennis',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#A7DD7C',
    colorActiveDark: '#A7DD7C',
  },
  {
    id: 5,
    name: 'Volleyball',
    iconName: 'gb-volleyball',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#FECB2F',
    colorActiveDark: '#FECB2F',
  },
  {
    id: 6,
    name: 'Basketball',
    iconName: 'gb-basketball',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#C87411',
    colorActiveDark: '#C87411',
  },
  {
    id: 7,
    name: 'Hockey',
    iconName: 'gb-hockey',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#558FFF',
    colorActiveDark: '#558FFF',
  },
  {
    id: 8,
    name: 'Handball',
    iconName: 'gb-handball',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#FFE0A3',
    colorActiveDark: '#FFE0A3',
  },
  {
    id: 9,
    name: 'Cricket',
    iconName: 'gb-cricket',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#A2A349',
    colorActiveDark: '#A2A349',
  },
  {
    id: 10,
    name: 'Mma',
    iconName: 'gb-mma',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#DB4A37',
    colorActiveDark: '#DB4A37',
  },
  {
    id: 11,
    name: 'Snooker',
    iconName: 'gb-snooker',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#49997C',
    colorActiveDark: '#49997C',
  },
  {
    id: 12,
    name: 'W. Polo',
    iconName: 'gb-polo',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#55ADFF',
    colorActiveDark: '#55ADFF',
  },
  {
    id: 13,
    name: 'Netball',
    iconName: 'gb-netball',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#49997C',
    colorActiveDark: '#49997C',
  },
  {
    id: 14,
    name: 'Rugby',
    iconName: 'gb-rugby',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#C87411',
    colorActiveDark: '#C87411',
  },
  {
    id: 15,
    name: 'Darts',
    iconName: 'gb-darts',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#FFBF2E',
    colorActiveDark: '#FFBF2E',
  },
  {
    id: 16,
    name: 'Golf',
    iconName: 'gb-golf',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#52C41A',
    colorActiveDark: '#52C41A',
  },
  {
    id: 17,
    name: 'Formula 1',
    iconName: 'gb-formula',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#FF4D4F',
    colorActiveDark: '#FF4D4F',
  },
  {
    id: 18,
    name: 'Chess',
    iconName: 'gb-chess',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#FAAD14',
    colorActiveDark: '#FAAD14',
  },
  {
    id: 19,
    name: 'Cycling',
    iconName: 'gb-cycling',
    colorLight: '#AAAAAA',
    colorDark: '#AAAAAA',
    colorActiveLight: '#93B5E6',
    colorActiveDark: '#93B5E6',
  },
];
